### ISSUE TITLE
3.13 out

### ISSUE THREAD

**Issue by blacklightpy** [iFoundSilentHouse/helio-sequencer-void-linux#1]
Update

**Comment by iFoundSilentHouse** [comment]
Thank you for your concerns! Updated: https://github.com/iFoundSilentHouse/helio-sequencer-void-linux/releases/tag/3.13_1

**Comment by blacklightpy** [comment]
Btw JUCE is now under a free license as of their latest release. So I guess Helio can now be included in Void.

**Comment by iFoundSilentHouse** [comment]
But I don't see changes in license file for the latest version (7.0.12 downloaded from juce site). Could you point on the license changes please?

**Comment by blacklightpy** [comment]
Oops actually it's only for JUCE 8, which isn't released yet. The preview is available on the `juce8` branch.

https://forum.juce.com/t/the-juce-8-preview-branch-is-available-now/60950
